/*
 * DeepL API Documentation
 *
 * The DeepL API provides programmatic access to DeepL’s machine translation technology.
 *
 * The version of the OpenAPI document: 2.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetLanguages200ResponseInner {
    /// The language code of the given language.
    #[serde(rename = "language")]
    pub language: String,
    /// Name of the language in English.
    #[serde(rename = "name")]
    pub name: String,
    /// Denotes formality support in case of a target language listing.
    #[serde(rename = "supports_formality", skip_serializing_if = "Option::is_none")]
    pub supports_formality: Option<bool>,
}

impl GetLanguages200ResponseInner {
    pub fn new(language: String, name: String) -> GetLanguages200ResponseInner {
        GetLanguages200ResponseInner {
            language,
            name,
            supports_formality: None,
        }
    }
}


