/*
 * DeepL API Documentation
 *
 * The DeepL API provides programmatic access to DeepL’s machine translation technology.
 *
 * The version of the OpenAPI document: 2.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetUsage200Response {
    /// Characters translated so far in the current billing period.
    #[serde(rename = "character_count", skip_serializing_if = "Option::is_none")]
    pub character_count: Option<i64>,
    /// Current maximum number of characters that can be translated per billing period.
    #[serde(rename = "character_limit", skip_serializing_if = "Option::is_none")]
    pub character_limit: Option<i64>,
    /// Documents translated so far in the current billing period.
    #[serde(rename = "document_limit", skip_serializing_if = "Option::is_none")]
    pub document_limit: Option<i64>,
    /// Current maximum number of documents that can be translated per billing period.
    #[serde(rename = "document_count", skip_serializing_if = "Option::is_none")]
    pub document_count: Option<i64>,
    /// Documents translated by all users in the team so far in the current billing period.
    #[serde(rename = "team_document_limit", skip_serializing_if = "Option::is_none")]
    pub team_document_limit: Option<i64>,
    /// Current maximum number of documents that can be translated by the team per billing period.
    #[serde(rename = "team_document_count", skip_serializing_if = "Option::is_none")]
    pub team_document_count: Option<i64>,
}

impl GetUsage200Response {
    pub fn new() -> GetUsage200Response {
        GetUsage200Response {
            character_count: None,
            character_limit: None,
            document_limit: None,
            document_count: None,
            team_document_limit: None,
            team_document_count: None,
        }
    }
}


