/*
 * DeepL API Documentation
 *
 * The DeepL API provides programmatic access to DeepL’s machine translation technology.
 *
 * The version of the OpenAPI document: 2.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListGlossaryLanguages200ResponseSupportedLanguagesInner {
    /// The language in which the source texts in the glossary are specified.
    #[serde(rename = "source_lang")]
    pub source_lang: String,
    /// The language in which the target texts in the glossary are specified.
    #[serde(rename = "target_lang")]
    pub target_lang: String,
}

impl ListGlossaryLanguages200ResponseSupportedLanguagesInner {
    pub fn new(source_lang: String, target_lang: String) -> ListGlossaryLanguages200ResponseSupportedLanguagesInner {
        ListGlossaryLanguages200ResponseSupportedLanguagesInner {
            source_lang,
            target_lang,
        }
    }
}


